server:
   port: 26000

web:
  client:
    interface-api-url: http://localhost:26001/esb/api/interface

file:
  transfer:
    temp-directory: /home/indigo/temp-file

spring:
  profiles:
    active: sender
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
