server:
   port: 26000

web:
  client:
    interface-api-url: http://localhost:26001/esb/api/interface/receive-data

spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:SQL_*.xml