server:
   port: 26000

spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:SQL_*.xml